env:
    browser: true
    commonjs: true
    es2021: true
    node: true
    webextensions: true
extends: ["eslint:recommended", "prettier"]
overrides: []
parserOptions:
    ecmaVersion: latest
rules: {}
